import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Ovo, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const nunito = Nunito({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ovo = Ovo({
  weight: ['400'],
  variable: "--font-ovo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Incident Report Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${nunito.variable} ${ovo.variable}`}>
        {children}
      </body>
    </html>
  );
}
